---
# tasks file for capture_config
- name: Copy configurations from artifactory using REST endpoint
  uri:
    url: "{{rest_query_url}}"
    method: GET
    user: "{{api_username}}"
    password: "{{api_password}}"
    headers:
      Accept: "application/xml"
    force_basic_auth: yes
    return_content: yes
    dest: "{{ playbook_dir }}/{{ config_file_path }}"

- name: Parse artifactory config in xml and create repo yaml
  script: ./create_repo_yaml.py {{ playbook_dir }}
  args:
    executable: python