---
# tasks file for deploy_config
- name: Deploy artifactory repo prerequesites - Proxy Config
  uri: &uri-definition
    url: "{{rest_query_url}}"
    method: PATCH
    user: "{{api_username}}"
    password: "{{api_password}}"
    headers:
      Content-Type: "application/yaml"
    force_basic_auth: yes
    return_content: yes
    src: "{{ item }}"
  with_fileglob: "{{ playbook_dir }}/{{ proxy_fileglob }}"

- name: Deploy artifactory repo prerequesites - PropertySet
  uri: *uri-definition
  with_fileglob: "{{ playbook_dir }}/{{ property_fileglob }}"

- name: Deploy artifactory LOCAL REPO configurations using REST endpoint
  uri: *uri-definition
  with_fileglob: "{{ playbook_dir }}/{{ local_fileglob }}"

- name: Deploy artifactory REMOTE REPO using REST endpoint
  uri: *uri-definition
  with_fileglob: "{{ playbook_dir }}/{{ remote_fileglob }}"

- name: Deploy artifactory VIRTUAL REPO using REST endpoint
  uri: *uri-definition
  with_fileglob: "{{ playbook_dir }}/{{ virtual_fileglob }}"