---
# tasks file for deploy_config
- name: Deploy repo configurations in files directory using REST endpoint
  uri:
    url: http://localhost:8084/artifactory/api/system/configuration
    method: PATCH
    user: admin
    password: admin123
    headers:
      Content-Type: "application/yaml"
    force_basic_auth: yes
    return_content: yes
    src: "{{ item }}"
  with_fileglob: "{{ playbook_dir }}/deploy_config/files/*.yml"
