---
# tasks file for deploy_config
- name: Deploy artifactory repo configurations from files directory using REST endpoint
  uri:
    url: "{{rest_query_url}}"
    method: PATCH
    user: "{{api_username}}"
    password: "{{api_password}}"
    headers:
      Content-Type: "application/yaml"
    force_basic_auth: yes
    return_content: yes
    src: "{{ item }}"
  with_fileglob: "{{ playbook_dir }}/{{ config_fileglob }}"
